[fileHashes]
"/home/novous/Desktop/git/spaceHoleAndPiracy/src/objects.d" = "35dcb69c"
"/home/novous/Desktop/git/spaceHoleAndPiracy/src/worldmod.d" = "9fd75bca"
"/home/novous/Desktop/git/spaceHoleAndPiracy/src/app.d" = "e1d24f93"
"/home/novous/Desktop/git/spaceHoleAndPiracy/src/utility.d" = "e3731432"
"/home/novous/Desktop/git/spaceHoleAndPiracy/src/mapmod.d" = "941fc450"
"/home/novous/Desktop/git/spaceHoleAndPiracy/src/timing.d" = "c9dcbe5c"
